Controllers films users
Tulpanchik2906/java-filmorate pull request #6
Opened 2023-02-23 17:18 UTC by Tulpanchik2906

Версия с ТЗ-9 для ревью

2023-02-24 17:25 UTC, Fleaman777 requested changes

2023-02-24 17:25 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +        generateId++;
инкрементацию айдишника можно было бы вынести в отдельный приватный метод, если вдруг нужно будет поменять реализацию инкрементации айди, это будет удобно сделать в 1 месте.

к тому же сам метод немного упростится,
можно будет сделать int id = incrementId(), 
а потом внутри метода использовать этот айди

2023-02-24 17:25 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
> +        generateId++;
аналагично с film

2023-02-24 17:25 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +    @NotBlank(message = "Название фильма не может быть состоять только из пробелов")
молодец, что решил использовать аннотации для валидации, с ними все выглядит лучше и работает оптимальней

2023-02-24 17:25 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +        );
т.к. текст достаточно большой, его можно было бы вынести в константу, для лучшего восприятия теста

2023-02-24 17:25 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +                        .value("user@yandex.ru"))
user@yandex.ru" , Name user, Login user хорошо бы было бы вынести в константы, что бы не дублировать написание этих значений в разных тестах, а просто использовать константы

2023-02-24 17:25 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controllers/UserControllerTest.java
> +    }
суперские тесты, настоящие интеграционные
+покрывают все необходимые кейсы

2023-02-25 07:11 UTC, Tulpanchik2906 commented
в следующем пулл-реквесте будут правки по замечаниям

2023-02-25 07:11 UTC, closed without merging

2023-02-25 16:49 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    private int generateId(){
супер, то, что нужно

2023-02-25 16:49 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controllers/FilmControllerTest.java
> +        String descriptionStr = "Пятеро друзей ( комик-группа «Шарло»), " +
можно даже сделать не просто локальную переменную, а константу