Версия, проходящая postman-тесты, без работающих unit-тестов
Tulpanchik2906/java-filmorate pull request #9
Opened 2023-03-28 18:29 UTC by Tulpanchik2906

Работа с jdbc, спринт - 11

2023-03-31 18:29 UTC, Fleaman777 requested changes

2023-03-31 18:29 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/models/Genre.java
> +public class Genre implements Comparable<Genre> {
хороший подход с тем, что бы имплементировать интерфейс |Comparable

2023-03-31 18:29 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        return user.getFriendsIds().stream().map(userStorage::getUserById).collect(Collectors.toList());
стрим лучше будет восприниматься, если сделать его в стрим формате: 
каждый метод на своей строке

2023-03-31 18:29 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDao.java
> +    }
можно немного разюить метод, и некоторые условия вынести в приватные методы, 
так метод add будет покороче, а следовательно и код будет чуть лучше читаться

2023-03-31 18:29 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDao.java
> +    }
здесь аналагично с пред комментарием

2023-03-31 18:29 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDao.java
> +        film.setLikeUserIds(getLikes(film.getId()));
для просечивания большого количества полей в один объект, хорошо использовать builder, 
так и производительность будет получше и восприниматься проще

2023-03-31 18:29 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDao.java
> +                    + acceptorId + "стала односторонней.");
для доблавения аргументов в лог лучше использовать плейсхолдер {} 
преимущества аналагичные с билдером, производительность и восприятие лучше

2023-03-31 18:29 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDao.java
> +            log.info("Дружба между " + initiatorId + " и " + acceptorId + "разорвана.");
здесь аналагично с пред. комментарием 

и в др. похожих местах

2023-03-31 18:29 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDao.java
> +        user.setFriendsIds(new TreeSet<>(getFriendsByUserId(user.getId())));
тоже можно использовать билдер

2023-03-31 18:29 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/FilmDaoTest.java
> +        filmStorage.add(film);
общую часть для всех тестов, можно вынести в метод с аннотацией @BeforeEach

2023-03-31 18:29 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/UserDaoTest.java
> +        userStorage.add(user);
в этих тестах тоже есть общая часть, которую можно было бы вынести в @BeforeEach

2023-04-01 19:07 UTC, Tulpanchik2906 commented on src/test/java/ru/yandex/practicum/filmorate/storage/dao/FilmDaoTest.java
> +        filmStorage.add(film);
Не стала выносить в before, чтобы легче было отслеживать тестовые данные, у меня есть тесты, где создание объекта фильм не нужно.

2023-04-02 14:48 UTC, Fleaman777 approved these changes

2023-04-02 14:48 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDao.java
> +        addRatingMpaByFilm(film);
отлично, то, что нужно

2023-04-11 07:02 UTC, Tulpanchik2906 commented
ревьювер принял работу

2023-04-11 07:02 UTC, merged